<a href="https://colab.research.google.com/github/PabloDuranL/Aplicaciones/blob/main/Pandapractica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [19]:
data=pd.Series([3,5,2,6])
data,data.values,data.index

(0    3
 1    5
 2    2
 3    6
 dtype: int64,
 array([3, 5, 2, 6]),
 RangeIndex(start=0, stop=4, step=1))

In [20]:
data[1],data[1:3], data[:-1]

(np.int64(5),
 1    5
 2    2
 dtype: int64,
 0    3
 1    5
 2    2
 dtype: int64)

In [21]:
data=pd.Series([3,5,2,6], index=['messi','ronaldo','ilya','lasha'])
data['messi'],data

(np.int64(3),
 messi      3
 ronaldo    5
 ilya       2
 lasha      6
 dtype: int64)

In [22]:
xd={'messi':5,'ilya':56,'lasha':45}
data=pd.Series(xd)
data, data['messi']

(messi     5
 ilya     56
 lasha    45
 dtype: int64,
 np.int64(5))

In [23]:
data['messi':'ilya']

messi     5
ilya     56
dtype: int64

In [24]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1,2,3])

1    b
2    a
3    c
dtype: object

In [25]:
snatch_dict={'ilya':198,'lasha':225,'nassar':188,'pablo':105}
cleanandjerk_dict={'ilya':262,'lasha':267,'nassar':228,'pablo':120}

snatch=pd.Series(snatch_dict)
cleanandjerk=pd.Series(cleanandjerk_dict)
marcas=pd.DataFrame({'mejor snatch':snatch_dict, 'mejor envion':cleanandjerk_dict})
marcas, marcas.index, marcas.columns

(        mejor snatch  mejor envion
 ilya             198           262
 lasha            225           267
 nassar           188           228
 pablo            105           120,
 Index(['ilya', 'lasha', 'nassar', 'pablo'], dtype='object'),
 Index(['mejor snatch', 'mejor envion'], dtype='object'))

In [26]:
marcas['mejor snatch']

ilya      198
lasha     225
nassar    188
pablo     105
Name: mejor snatch, dtype: int64

In [27]:
pd.DataFrame(snatch,columns=['mejor snatch'])

        mejor snatch
ilya             198
lasha            225
nassar           188
pablo            105

In [28]:
data = [{'a': i, 'b': 2 * i}
        for i in range(6)]
pd.DataFrame(data)

   a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10

In [29]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}], index=[9,3])

     a  b    c
9  1.0  2  NaN
3  NaN  3  4.0

In [30]:
x=np.random.randint(100,200, size=(4,3))
x

array([[148, 166, 110],
       [161, 187, 106],
       [180, 138, 155],
       [115, 182, 163]])

In [31]:
resultados=pd.DataFrame(x,columns=['arr','env','sent'], index=['pablo','lasha','ilya','klokov'])

In [32]:
resultados['total']= resultados['arr']+resultados['env']
resultados

        arr  env  sent  total
pablo   148  166   110    314
lasha   161  187   106    348
ilya    180  138   155    318
klokov  115  182   163    297

In [39]:
resultados.loc['ilya']

arr      180
env      138
sent     155
total    318
Name: ilya, dtype: int64

In [42]:
resultados - resultados.loc['ilya']

        arr  env  sent  total
pablo   -32   28   -45     -4
lasha   -19   49   -49     30
ilya      0    0     0      0
klokov  -65   44     8    -21

In [33]:
ind = pd.Index([2,3])
ind

Index([2, 3], dtype='int64')

In [34]:
edad_d={'sally':2,'pucca':6}
peso_d={'sally':7, 'pucca':15}
edad=pd.Series(edad_d)
peso=pd.Series(peso_d)
pd.DataFrame({'edad':edad_d,'peso':peso_d})

       edad  peso
sally     2     7
pucca     6    15

In [49]:
resultados.iloc[0:2]

       arr  env  sent  total
pablo  148  166   110    314
lasha  161  187   106    348

In [50]:
resultados.iloc[0]

arr      148
env      166
sent     110
total    314
Name: pablo, dtype: int64

In [57]:
resultados.loc[resultados.arr>150,'env']

lasha    187
ilya     138
Name: env, dtype: int64

In [59]:
resultados.loc[resultados.arr>150,['total','sent']]

       total  sent
lasha    348   106
ilya     318   155

In [61]:
resultados.iloc[0,3]=200
resultados

        arr  env  sent  total
pablo   148  166   110    200
lasha   161  187   106    348
ilya    180  138   155    318
klokov  115  182   163    297

In [64]:
resultados.loc[::2,['total','sent']]=[200,209]
resultados

          arr    env   sent  total
pablo   148.0  166.0  209.0  200.0
lasha   161.0  187.0  106.0  348.0
ilya    180.0  138.0  209.0  200.0
klokov  115.0  182.0  163.0  297.0
0         NaN    NaN  209.0  200.0

In [69]:
df = pd.DataFrame(np.random.randint(0, 10, size=(3, 4)),
                  columns=list('ABCD'))
df

   A  B  C  D
0  2  0  6  4
1  5  4  2  3
2  1  4  9  5

In [88]:
rng=np.random.RandomState(4)
rng.randint(150,200)

196