<a href="https://colab.research.google.com/github/PabloDuranL/Aplicaciones/blob/main/Pandapractica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [ ]:
data=pd.Series([3,5,2,6])
data,data.values,data.index

(0    3
 1    5
 2    2
 3    6
 dtype: int64,
 array([3, 5, 2, 6]),
 RangeIndex(start=0, stop=4, step=1))

In [ ]:
data[1],data[1:3], data[:-1]

(np.int64(5),
 1    5
 2    2
 dtype: int64,
 0    3
 1    5
 2    2
 dtype: int64)

In [ ]:
data=pd.Series([3,5,2,6], index=['messi','ronaldo','ilya','lasha'])
data['messi'],data

(np.int64(3),
 messi      3
 ronaldo    5
 ilya       2
 lasha      6
 dtype: int64)

In [ ]:
xd={'messi':5,'ilya':56,'lasha':45}
data=pd.Series(xd)
data, data['messi']

(messi     5
 ilya     56
 lasha    45
 dtype: int64,
 np.int64(5))

In [ ]:
data['messi':'ilya']

messi     5
ilya     56
dtype: int64

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1,2,3])

1    b
2    a
3    c
dtype: object

In [ ]:
snatch_dict={'ilya':198,'lasha':225,'nassar':188,'pablo':105}
cleanandjerk_dict={'ilya':262,'lasha':267,'nassar':228,'pablo':120}

snatch=pd.Series(snatch_dict)
cleanandjerk=pd.Series(cleanandjerk_dict)
marcas=pd.DataFrame({'mejor snatch':snatch_dict, 'mejor envion':cleanandjerk_dict})
marcas, marcas.index, marcas.columns

(        mejor snatch  mejor envion
 ilya             198           262
 lasha            225           267
 nassar           188           228
 pablo            105           120,
 Index(['ilya', 'lasha', 'nassar', 'pablo'], dtype='object'),
 Index(['mejor snatch', 'mejor envion'], dtype='object'))

In [ ]:
marcas['mejor snatch']

ilya      198
lasha     225
nassar    188
pablo     105
Name: mejor snatch, dtype: int64

In [ ]:
pd.DataFrame(snatch,columns=['mejor snatch'])

        mejor snatch
ilya             198
lasha            225
nassar           188
pablo            105

In [ ]:
data = [{'a': i, 'b': 2 * i}
        for i in range(6)]
pd.DataFrame(data)

   a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10

In [ ]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}], index=[9,3])

     a  b    c
9  1.0  2  NaN
3  NaN  3  4.0

In [ ]:
pd.DataFrame({'a': 1, 'b': 2})

      a  b
pene  1  2

In [ ]:
x=np.random.randint(100,200, size=(4,3))
x

array([[143, 160, 172],
       [170, 128, 157],
       [159, 172, 133],
       [142, 178, 152]])

In [ ]:
resultados=pd.DataFrame(x,columns=['arr','env','sent'], index=['pablo','lasha','ilya','klokov'])

        arr  env  sent
pablo   143  160   172
lasha   170  128   157
ilya    159  172   133
klokov  142  178   152

In [ ]:
ind = pd.Index([2,3])
ind

Index([2, 3], dtype='int64')

In [ ]:
edad_d={'sally':2,'pucca':6}
peso_d={'sally':7, 'pucca':15}
edad=pd.Series(edad_d)
peso=pd.Series(peso_d)
pd.DataFrame({'edad':edad_d,'peso':peso_d})

       edad  peso
sally     2     7
pucca     6    15

In [ ]:
pd.DataFrame(peso,columns=['peso de estas marranas'])

       peso de estas marranas
sally                       7
pucca                      15