<a href="https://colab.research.google.com/github/PabloDuranL/Aplicaciones/blob/main/Pandapractica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [2]:
data=pd.Series([3,5,2,6])
data,data.values,data.index

(0    3
 1    5
 2    2
 3    6
 dtype: int64,
 array([3, 5, 2, 6]),
 RangeIndex(start=0, stop=4, step=1))

In [3]:
data[1],data[1:3], data[:-1]

(np.int64(5),
 1    5
 2    2
 dtype: int64,
 0    3
 1    5
 2    2
 dtype: int64)

In [4]:
data=pd.Series([3,5,2,6], index=['messi','ronaldo','ilya','lasha'])
data['messi'],data

(np.int64(3),
 messi      3
 ronaldo    5
 ilya       2
 lasha      6
 dtype: int64)

In [5]:
xd={'messi':5,'ilya':56,'lasha':45}
data=pd.Series(xd)
data, data['messi']

(messi     5
 ilya     56
 lasha    45
 dtype: int64,
 np.int64(5))

In [6]:
data['messi':'ilya']

messi     5
ilya     56
dtype: int64

In [7]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1,2,3])

1    b
2    a
3    c
dtype: object

In [8]:
snatch_dict={'ilya':198,'lasha':225,'nassar':188,'pablo':105}
cleanandjerk_dict={'ilya':262,'lasha':267,'nassar':228,'pablo':120}

snatch=pd.Series(snatch_dict)
cleanandjerk=pd.Series(cleanandjerk_dict)
marcas=pd.DataFrame({'mejor snatch':snatch_dict, 'mejor envion':cleanandjerk_dict})
marcas, marcas.index, marcas.columns

(        mejor snatch  mejor envion
 ilya             198           262
 lasha            225           267
 nassar           188           228
 pablo            105           120,
 Index(['ilya', 'lasha', 'nassar', 'pablo'], dtype='object'),
 Index(['mejor snatch', 'mejor envion'], dtype='object'))

In [9]:
marcas['mejor snatch']

ilya      198
lasha     225
nassar    188
pablo     105
Name: mejor snatch, dtype: int64

In [10]:
pd.DataFrame(snatch,columns=['mejor snatch'])

        mejor snatch
ilya             198
lasha            225
nassar           188
pablo            105

In [11]:
data = [{'a': i, 'b': 2 * i}
        for i in range(6)]
pd.DataFrame(data)

   a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10

In [12]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}], index=[9,3])

     a  b    c
9  1.0  2  NaN
3  NaN  3  4.0

In [13]:
x=np.random.randint(100,200, size=(4,3))
x

array([[191, 158, 114],
       [146, 161, 115],
       [121, 163, 186],
       [182, 144, 180]])

In [14]:
resultados=pd.DataFrame(x,columns=['arr','env','sent'], index=['pablo','lasha','ilya','klokov'])

In [15]:
resultados['total']= resultados['arr']+resultados['env']
resultados

        arr  env  sent  total
pablo   191  158   114    349
lasha   146  161   115    307
ilya    121  163   186    284
klokov  182  144   180    326

In [16]:
resultados.loc['ilya']

arr      121
env      163
sent     186
total    284
Name: ilya, dtype: int64

In [17]:
resultados - resultados.loc['ilya']

        arr  env  sent  total
pablo    70   -5   -72     65
lasha    25   -2   -71     23
ilya      0    0     0      0
klokov   61  -19    -6     42

In [18]:
ind = pd.Index([2,3])
ind

Index([2, 3], dtype='int64')

In [19]:
edad_d={'sally':2,'pucca':6}
peso_d={'sally':7, 'pucca':15}
edad=pd.Series(edad_d)
peso=pd.Series(peso_d)
pd.DataFrame({'edad':edad_d,'peso':peso_d})

       edad  peso
sally     2     7
pucca     6    15

In [20]:
resultados.iloc[0:2]

       arr  env  sent  total
pablo  191  158   114    349
lasha  146  161   115    307

In [21]:
resultados.iloc[0]

arr      191
env      158
sent     114
total    349
Name: pablo, dtype: int64

In [22]:
resultados.loc[resultados.arr>150,'env']

pablo     158
klokov    144
Name: env, dtype: int64

In [23]:
resultados.loc[resultados.arr>150,['total','sent']]

        total  sent
pablo     349   114
klokov    326   180

In [24]:
resultados.iloc[0,3]=200
resultados

        arr  env  sent  total
pablo   191  158   114    200
lasha   146  161   115    307
ilya    121  163   186    284
klokov  182  144   180    326

In [25]:
resultados.loc[::2,['total','sent']]=[200,209]
resultados

        arr  env  sent  total
pablo   191  158   209    200
lasha   146  161   115    307
ilya    121  163   209    200
klokov  182  144   180    326

In [26]:
df = pd.DataFrame(np.random.randint(0, 10, size=(3, 4)),
                  columns=list('ABCD'))
df

   A  B  C  D
0  2  9  1  7
1  8  4  1  2
2  1  5  7  1

In [27]:
rng=np.random.RandomState(4)
rng.randint(150,200)

196

In [28]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

df.dropna(axis='columns')

   2
0  2
1  5
2  6

In [29]:
x=np.random.rand(3,3)
y=np.random.rand(3)
np.hstack((x, y[:, np.newaxis]))
np.vstack((x,y)), y[:,np.newaxis].shape

(array([[0.52612699, 0.38804933, 0.40352734],
        [0.11159898, 0.20746644, 0.12865711],
        [0.68585547, 0.27380664, 0.39592634],
        [0.88756132, 0.96195482, 0.53279552]]),
 (3, 1))

In [30]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [31]:
data.fillna(6)

a    1.0
b    6.0
c    2.0
d    6.0
e    3.0
dtype: float64

In [32]:
data.fillna(method='ffill')

/tmp/ipykernel_3335/1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [33]:
data.fillna(method='bfill')

/tmp/ipykernel_3335/1397359497.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [34]:
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [35]:
df.fillna(method='ffill', axis=0)

/tmp/ipykernel_3335/3122255136.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=0)

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6

In [36]:
df.dropna()

     0    1  2
1  2.0  3.0  5

In [37]:
index=[('ilya',2008),('ilya',2012)]
snatch=np.array([345,367])
envion=np.array([343,345])
marcas=[snatch,envion]
df = pd.DataFrame(marcas, index=index) # Create DataFrame with default column names
df.columns = ['Mejor total','Mejor envion'] # Assign desired column names
df

              Mejor total  Mejor envion
(ilya, 2008)          345           367
(ilya, 2012)          343           345

In [38]:
index = pd.MultiIndex.from_tuples(index)
index
df.reindex(index)

           Mejor total  Mejor envion
ilya 2008          345           367
     2012          343           345

In [39]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [40]:
pop[('California',2000):('New York',2010)]

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
dtype: int64

In [41]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [42]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [43]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [44]:
pop_df=pop.unstack()
pop_df

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [45]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [46]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

                    total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [47]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [48]:
f_u18.unstack()

                2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [49]:
f_u18.unstack(level=0)

      California  New York     Texas
2000    0.273594  0.247010  0.283251
2010    0.249211  0.222831  0.273568

In [50]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

        data1     data2
a 1  0.701305  0.018124
  2  0.979125  0.980692
b 1  0.232431  0.328392
  2  0.680710  0.636115

In [51]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [52]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [53]:
pop_flat = pop.reset_index(name='xdddd')
pop_flat

        state  year     xdddd
0  California  2000  33871648
1  California  2010  37253956
2    New York  2000  18976457
3    New York  2010  19378102
4       Texas  2000  20851820
5       Texas  2010  25145561

In [54]:
pop_flat.set_index(['state', 'year'])

                    xdddd
state      year
California 2000  33871648
           2010  37253956
New York   2000  18976457
           2010  19378102
Texas      2000  20851820
           2010  25145561

In [55]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [56]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [57]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z], axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [59]:
# Original Signature in Pandas v0.18 (for reference)
# pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
#           keys=None, levels=None, names=None, verify_integrity=False,
#           copy=True)

# Example of how to correctly use pd.concat with existing DataFrames
# Concatenating 'resultados' and 'pop_df' along columns (axis=1)
# Note: These DataFrames have different indices, so an outer join will be used,
# and some NaN values will likely appear where indices don't match.
pd.concat([resultados, pop_df], axis=0, join='outer')

                      arr    env   sent     total    under18
pablo               191.0  158.0  209.0       200        NaN
lasha               146.0  161.0  115.0       307        NaN
ilya                121.0  163.0  209.0       200        NaN
klokov              182.0  144.0  180.0       326        NaN
(California, 2000)    NaN    NaN    NaN  33871648  9267089.0
(California, 2010)    NaN    NaN    NaN  37253956  9284094.0
(New York, 2000)      NaN    NaN    NaN  18976457  4687374.0
(New York, 2010)      NaN    NaN    NaN  19378102  4318033.0
(Texas, 2000)         NaN    NaN    NaN  20851820  5906301.0
(Texas, 2010)         NaN    NaN    NaN  25145561  6879014.0

In [60]:
pd.concat([resultados, pop_df], axis=1, join='outer' )

                      arr    env   sent  total       total    under18
pablo               191.0  158.0  209.0  200.0         NaN        NaN
lasha               146.0  161.0  115.0  307.0         NaN        NaN
ilya                121.0  163.0  209.0  200.0         NaN        NaN
klokov              182.0  144.0  180.0  326.0         NaN        NaN
(California, 2000)    NaN    NaN    NaN    NaN  33871648.0  9267089.0
(California, 2010)    NaN    NaN    NaN    NaN  37253956.0  9284094.0
(New York, 2000)      NaN    NaN    NaN    NaN  18976457.0  4687374.0
(New York, 2010)      NaN    NaN    NaN    NaN  19378102.0  4318033.0
(Texas, 2000)         NaN    NaN    NaN    NaN  20851820.0  5906301.0
(Texas, 2010)         NaN    NaN    NaN    NaN  25145561.0  6879014.0

In [61]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [62]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
display('df1', 'df2', 'pd.concat([df1, df2])')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

pd.concat([df1, df2])
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [63]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
display('df3', 'df4', "pd.concat([df3, df4], axis=1)")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis=1)
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [64]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index
display('x', 'y', 'pd.concat([x, y])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [65]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Index([0, 1], dtype='int64')

In [66]:
display('x', 'y', 'pd.concat([x, y], ignore_index=True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], ignore_index=True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [67]:
display('x', 'y', "pd.concat([x, y], keys=['ah', 'simon'])")

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], keys=['ah', 'simon'])
          A   B
ah    0  A0  B0
      1  A1  B1
simon 0  A2  B2
      1  A3  B3

In [68]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
display('df5', 'df6', 'pd.concat([df5, df6])')

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [69]:
display('df5', 'df6',
        "pd.concat([df5, df6], join='inner')") #inner regresa solo aquellos que no daran NaN en ningun valor de la columna

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join='inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [70]:
display('df5', 'df6', "pd.concat([df5, df6])[df5.columns]")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])[df5.columns]
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [71]:
display('df1', 'df2', 'pd.concat([df1, df2])')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

pd.concat([df1, df2])
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [72]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [73]:
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [74]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'df4', 'pd.merge(df3, df4)')

df3
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

df4
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

pd.merge(df3, df4)
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [75]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
display('df1', 'df5', "pd.merge(df1, df5)")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df5
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

pd.merge(df1, df5)
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [76]:
display('df1', 'df2', "pd.merge(df1, df2, on='employee')")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

pd.merge(df1, df2, on='employee')
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [77]:
display('df1', 'df2', "pd.merge(df1, df2)")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

pd.merge(df1, df2)
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [83]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display('df1', 'df3', 'pd.merge(df1, df3, left_on="employee", right_on="name")')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df3
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(df1, df3, left_on="employee", right_on="name")
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [90]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [91]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
display('df1a', 'df2a')

df1a
                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [97]:
display('df1a', 'df2a',
        "pd.merge(df1a, df2a, left_index=True, right_index=True)")

df1a
                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

pd.merge(df1a, df2a, left_index=True, right_index=True)
                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [98]:
display('df1a', 'df2a', 'df1a.join(df2a)')

df1a
                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

df1a.join(df2a)
                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [101]:
display('df1a', 'df3', "pd.merge(df1a, df3, left_index=True, right_on='name')")

df1a
                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df3
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(df1a, df3, left_index=True, right_on='name')
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

In [102]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
display('df6', 'df7', 'pd.merge(df6, df7)')

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7)
   name   food drink
0  Mary  bread  wine

In [103]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
display('df6', 'df7', 'pd.merge(df6, df7)')

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7)
   name   food drink
0  Mary  bread  wine

In [106]:
display('df6', 'df7', "df6.set_index('name').join(df7.set_index('name'))")

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

df6.set_index('name').join(df7.set_index('name'))
        food drink
name
Peter   fish   NaN
Paul   beans   NaN
Mary   bread  wine

In [107]:
pd.merge(df6, df7, on='name', how='outer')  "how='outer','left','right',inner donde outer=todos, left=izquierda, right=derecha, inner=coincidencias en ambas tablas se salvan"

     name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

In [108]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
display('df8', 'df9', 'pd.merge(df8, df9, on="name")')

df8
   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

df9
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

pd.merge(df8, df9, on="name")
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [111]:
display('df8', 'df9', 'pd.merge(df8, df9, on="name", suffixes=[" 2019", " 2020"])')

df8
   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

df9
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

pd.merge(df8, df9, on="name", suffixes=[" 2019", " 2020"])
   name  rank 2019  rank 2020
0   Bob          1          3
1  Jake          2          1
2  Lisa          3          4
3   Sue          4          2

In [113]:
# Following are shell commands to download the data
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57935  100 57935    0     0   158k      0 --:--:-- --:--:-- --:--:--  159k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   835  100   835    0     0   2158      0 --:--:-- --:--:-- --:--:--  2157
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   872  100   872    0     0   4131      0 --:--:-- --:--:-- --:--:--  4152

In [117]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

display('pop.head()', 'areas.head()', 'abbrevs.head()')

pop.head()
  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

areas.head()
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

abbrevs.head()
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA